bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j01_mvpa_perm > log_j01_mvpa_perm 2> err_j01_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j02_mvpa_perm > log_j02_mvpa_perm 2> err_j02_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j03_mvpa_perm > log_j03_mvpa_perm 2> err_j03_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j04_mvpa_perm > log_j04_mvpa_perm 2> err_j04_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j05_mvpa_perm > log_j05_mvpa_perm 2> err_j05_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j06_mvpa_perm > log_j06_mvpa_perm 2> err_j06_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j07_mvpa_perm > log_j07_mvpa_perm 2> err_j07_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j08_mvpa_perm > log_j08_mvpa_perm 2> err_j08_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j09_mvpa_perm > log_j09_mvpa_perm 2> err_j09_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j10_mvpa_perm > log_j10_mvpa_perm 2> err_j10_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j11_mvpa_perm > log_j11_mvpa_perm 2> err_j11_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j12_mvpa_perm > log_j12_mvpa_perm 2> err_j12_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j13_mvpa_perm > log_j13_mvpa_perm 2> err_j13_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j14_mvpa_perm > log_j14_mvpa_perm 2> err_j14_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j15_mvpa_perm > log_j15_mvpa_perm 2> err_j15_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j16_mvpa_perm > log_j16_mvpa_perm 2> err_j16_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j17_mvpa_perm > log_j17_mvpa_perm 2> err_j17_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j18_mvpa_perm > log_j18_mvpa_perm 2> err_j18_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j19_mvpa_perm > log_j19_mvpa_perm 2> err_j19_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j20_mvpa_perm > log_j20_mvpa_perm 2> err_j20_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j21_mvpa_perm > log_j21_mvpa_perm 2> err_j21_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j22_mvpa_perm > log_j22_mvpa_perm 2> err_j22_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j23_mvpa_perm > log_j23_mvpa_perm 2> err_j23_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j24_mvpa_perm > log_j24_mvpa_perm 2> err_j24_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j25_mvpa_perm > log_j25_mvpa_perm 2> err_j25_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j26_mvpa_perm > log_j26_mvpa_perm 2> err_j26_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j27_mvpa_perm > log_j27_mvpa_perm 2> err_j27_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j28_mvpa_perm > log_j28_mvpa_perm 2> err_j28_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j29_mvpa_perm > log_j29_mvpa_perm 2> err_j29_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j30_mvpa_perm > log_j30_mvpa_perm 2> err_j30_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j31_mvpa_perm > log_j31_mvpa_perm 2> err_j31_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j32_mvpa_perm > log_j32_mvpa_perm 2> err_j32_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j33_mvpa_perm > log_j33_mvpa_perm 2> err_j33_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j34_mvpa_perm > log_j34_mvpa_perm 2> err_j34_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j35_mvpa_perm > log_j35_mvpa_perm 2> err_j35_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j36_mvpa_perm > log_j36_mvpa_perm 2> err_j36_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j37_mvpa_perm > log_j37_mvpa_perm 2> err_j37_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j38_mvpa_perm > log_j38_mvpa_perm 2> err_j38_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j39_mvpa_perm > log_j39_mvpa_perm 2> err_j39_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j40_mvpa_perm > log_j40_mvpa_perm 2> err_j40_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j41_mvpa_perm > log_j41_mvpa_perm 2> err_j41_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j42_mvpa_perm > log_j42_mvpa_perm 2> err_j42_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j43_mvpa_perm > log_j43_mvpa_perm 2> err_j43_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j44_mvpa_perm > log_j44_mvpa_perm 2> err_j44_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j45_mvpa_perm > log_j45_mvpa_perm 2> err_j45_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j46_mvpa_perm > log_j46_mvpa_perm 2> err_j46_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j47_mvpa_perm > log_j47_mvpa_perm 2> err_j47_mvpa_perm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/mvpa_perm/j48_mvpa_perm > log_j48_mvpa_perm 2> err_j48_mvpa_perm 
