bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j01_aud_glm > log_j01_aud_glm 2> err_j01_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j02_aud_glm > log_j02_aud_glm 2> err_j02_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j03_aud_glm > log_j03_aud_glm 2> err_j03_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j04_aud_glm > log_j04_aud_glm 2> err_j04_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j05_aud_glm > log_j05_aud_glm 2> err_j05_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j06_aud_glm > log_j06_aud_glm 2> err_j06_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j07_aud_glm > log_j07_aud_glm 2> err_j07_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j08_aud_glm > log_j08_aud_glm 2> err_j08_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j09_aud_glm > log_j09_aud_glm 2> err_j09_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j10_aud_glm > log_j10_aud_glm 2> err_j10_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j11_aud_glm > log_j11_aud_glm 2> err_j11_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j12_aud_glm > log_j12_aud_glm 2> err_j12_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j13_aud_glm > log_j13_aud_glm 2> err_j13_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j14_aud_glm > log_j14_aud_glm 2> err_j14_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j15_aud_glm > log_j15_aud_glm 2> err_j15_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j16_aud_glm > log_j16_aud_glm 2> err_j16_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j17_aud_glm > log_j17_aud_glm 2> err_j17_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j18_aud_glm > log_j18_aud_glm 2> err_j18_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j19_aud_glm > log_j19_aud_glm 2> err_j19_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j20_aud_glm > log_j20_aud_glm 2> err_j20_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j21_aud_glm > log_j21_aud_glm 2> err_j21_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j22_aud_glm > log_j22_aud_glm 2> err_j22_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j23_aud_glm > log_j23_aud_glm 2> err_j23_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j24_aud_glm > log_j24_aud_glm 2> err_j24_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j25_aud_glm > log_j25_aud_glm 2> err_j25_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j26_aud_glm > log_j26_aud_glm 2> err_j26_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j27_aud_glm > log_j27_aud_glm 2> err_j27_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j28_aud_glm > log_j28_aud_glm 2> err_j28_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j29_aud_glm > log_j29_aud_glm 2> err_j29_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j30_aud_glm > log_j30_aud_glm 2> err_j30_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j31_aud_glm > log_j31_aud_glm 2> err_j31_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j32_aud_glm > log_j32_aud_glm 2> err_j32_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j33_aud_glm > log_j33_aud_glm 2> err_j33_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j34_aud_glm > log_j34_aud_glm 2> err_j34_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j35_aud_glm > log_j35_aud_glm 2> err_j35_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j36_aud_glm > log_j36_aud_glm 2> err_j36_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j37_aud_glm > log_j37_aud_glm 2> err_j37_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j38_aud_glm > log_j38_aud_glm 2> err_j38_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j39_aud_glm > log_j39_aud_glm 2> err_j39_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j40_aud_glm > log_j40_aud_glm 2> err_j40_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j41_aud_glm > log_j41_aud_glm 2> err_j41_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j42_aud_glm > log_j42_aud_glm 2> err_j42_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j43_aud_glm > log_j43_aud_glm 2> err_j43_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j44_aud_glm > log_j44_aud_glm 2> err_j44_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j45_aud_glm > log_j45_aud_glm 2> err_j45_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j46_aud_glm > log_j46_aud_glm 2> err_j46_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j47_aud_glm > log_j47_aud_glm 2> err_j47_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j48_aud_glm > log_j48_aud_glm 2> err_j48_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j49_aud_glm > log_j49_aud_glm 2> err_j49_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j50_aud_glm > log_j50_aud_glm 2> err_j50_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j51_aud_glm > log_j51_aud_glm 2> err_j51_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j52_aud_glm > log_j52_aud_glm 2> err_j52_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j53_aud_glm > log_j53_aud_glm 2> err_j53_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j54_aud_glm > log_j54_aud_glm 2> err_j54_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j55_aud_glm > log_j55_aud_glm 2> err_j55_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j56_aud_glm > log_j56_aud_glm 2> err_j56_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j57_aud_glm > log_j57_aud_glm 2> err_j57_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j58_aud_glm > log_j58_aud_glm 2> err_j58_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j59_aud_glm > log_j59_aud_glm 2> err_j59_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j60_aud_glm > log_j60_aud_glm 2> err_j60_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j61_aud_glm > log_j61_aud_glm 2> err_j61_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j62_aud_glm > log_j62_aud_glm 2> err_j62_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j63_aud_glm > log_j63_aud_glm 2> err_j63_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j64_aud_glm > log_j64_aud_glm 2> err_j64_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j65_aud_glm > log_j65_aud_glm 2> err_j65_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j66_aud_glm > log_j66_aud_glm 2> err_j66_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j67_aud_glm > log_j67_aud_glm 2> err_j67_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j68_aud_glm > log_j68_aud_glm 2> err_j68_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j69_aud_glm > log_j69_aud_glm 2> err_j69_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j70_aud_glm > log_j70_aud_glm 2> err_j70_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j71_aud_glm > log_j71_aud_glm 2> err_j71_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j72_aud_glm > log_j72_aud_glm 2> err_j72_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j73_aud_glm > log_j73_aud_glm 2> err_j73_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j74_aud_glm > log_j74_aud_glm 2> err_j74_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j75_aud_glm > log_j75_aud_glm 2> err_j75_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j76_aud_glm > log_j76_aud_glm 2> err_j76_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j77_aud_glm > log_j77_aud_glm 2> err_j77_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j78_aud_glm > log_j78_aud_glm 2> err_j78_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j79_aud_glm > log_j79_aud_glm 2> err_j79_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j80_aud_glm > log_j80_aud_glm 2> err_j80_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j81_aud_glm > log_j81_aud_glm 2> err_j81_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j82_aud_glm > log_j82_aud_glm 2> err_j82_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j83_aud_glm > log_j83_aud_glm 2> err_j83_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j84_aud_glm > log_j84_aud_glm 2> err_j84_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j85_aud_glm > log_j85_aud_glm 2> err_j85_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j86_aud_glm > log_j86_aud_glm 2> err_j86_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j87_aud_glm > log_j87_aud_glm 2> err_j87_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j88_aud_glm > log_j88_aud_glm 2> err_j88_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j89_aud_glm > log_j89_aud_glm 2> err_j89_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j90_aud_glm > log_j90_aud_glm 2> err_j90_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j91_aud_glm > log_j91_aud_glm 2> err_j91_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j92_aud_glm > log_j92_aud_glm 2> err_j92_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j93_aud_glm > log_j93_aud_glm 2> err_j93_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j94_aud_glm > log_j94_aud_glm 2> err_j94_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j95_aud_glm > log_j95_aud_glm 2> err_j95_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j96_aud_glm > log_j96_aud_glm 2> err_j96_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j97_aud_glm > log_j97_aud_glm 2> err_j97_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j98_aud_glm > log_j98_aud_glm 2> err_j98_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j99_aud_glm > log_j99_aud_glm 2> err_j99_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j100_aud_glm > log_j100_aud_glm 2> err_j100_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j101_aud_glm > log_j101_aud_glm 2> err_j101_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j102_aud_glm > log_j102_aud_glm 2> err_j102_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j103_aud_glm > log_j103_aud_glm 2> err_j103_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j104_aud_glm > log_j104_aud_glm 2> err_j104_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j105_aud_glm > log_j105_aud_glm 2> err_j105_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j106_aud_glm > log_j106_aud_glm 2> err_j106_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j107_aud_glm > log_j107_aud_glm 2> err_j107_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j108_aud_glm > log_j108_aud_glm 2> err_j108_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j109_aud_glm > log_j109_aud_glm 2> err_j109_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j110_aud_glm > log_j110_aud_glm 2> err_j110_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j111_aud_glm > log_j111_aud_glm 2> err_j111_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j112_aud_glm > log_j112_aud_glm 2> err_j112_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j113_aud_glm > log_j113_aud_glm 2> err_j113_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j114_aud_glm > log_j114_aud_glm 2> err_j114_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j115_aud_glm > log_j115_aud_glm 2> err_j115_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j116_aud_glm > log_j116_aud_glm 2> err_j116_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j117_aud_glm > log_j117_aud_glm 2> err_j117_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j118_aud_glm > log_j118_aud_glm 2> err_j118_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j119_aud_glm > log_j119_aud_glm 2> err_j119_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j120_aud_glm > log_j120_aud_glm 2> err_j120_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j121_aud_glm > log_j121_aud_glm 2> err_j121_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j122_aud_glm > log_j122_aud_glm 2> err_j122_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j123_aud_glm > log_j123_aud_glm 2> err_j123_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j124_aud_glm > log_j124_aud_glm 2> err_j124_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j125_aud_glm > log_j125_aud_glm 2> err_j125_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j126_aud_glm > log_j126_aud_glm 2> err_j126_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j127_aud_glm > log_j127_aud_glm 2> err_j127_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j128_aud_glm > log_j128_aud_glm 2> err_j128_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j129_aud_glm > log_j129_aud_glm 2> err_j129_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j130_aud_glm > log_j130_aud_glm 2> err_j130_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j131_aud_glm > log_j131_aud_glm 2> err_j131_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j132_aud_glm > log_j132_aud_glm 2> err_j132_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j133_aud_glm > log_j133_aud_glm 2> err_j133_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j134_aud_glm > log_j134_aud_glm 2> err_j134_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j135_aud_glm > log_j135_aud_glm 2> err_j135_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j136_aud_glm > log_j136_aud_glm 2> err_j136_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j137_aud_glm > log_j137_aud_glm 2> err_j137_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j138_aud_glm > log_j138_aud_glm 2> err_j138_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j139_aud_glm > log_j139_aud_glm 2> err_j139_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j140_aud_glm > log_j140_aud_glm 2> err_j140_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j141_aud_glm > log_j141_aud_glm 2> err_j141_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j142_aud_glm > log_j142_aud_glm 2> err_j142_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j143_aud_glm > log_j143_aud_glm 2> err_j143_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j144_aud_glm > log_j144_aud_glm 2> err_j144_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j145_aud_glm > log_j145_aud_glm 2> err_j145_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j146_aud_glm > log_j146_aud_glm 2> err_j146_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j147_aud_glm > log_j147_aud_glm 2> err_j147_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j148_aud_glm > log_j148_aud_glm 2> err_j148_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j149_aud_glm > log_j149_aud_glm 2> err_j149_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j150_aud_glm > log_j150_aud_glm 2> err_j150_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j151_aud_glm > log_j151_aud_glm 2> err_j151_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j152_aud_glm > log_j152_aud_glm 2> err_j152_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j153_aud_glm > log_j153_aud_glm 2> err_j153_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j154_aud_glm > log_j154_aud_glm 2> err_j154_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j155_aud_glm > log_j155_aud_glm 2> err_j155_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j156_aud_glm > log_j156_aud_glm 2> err_j156_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j157_aud_glm > log_j157_aud_glm 2> err_j157_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j158_aud_glm > log_j158_aud_glm 2> err_j158_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j159_aud_glm > log_j159_aud_glm 2> err_j159_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j160_aud_glm > log_j160_aud_glm 2> err_j160_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j161_aud_glm > log_j161_aud_glm 2> err_j161_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j162_aud_glm > log_j162_aud_glm 2> err_j162_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j163_aud_glm > log_j163_aud_glm 2> err_j163_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j164_aud_glm > log_j164_aud_glm 2> err_j164_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j165_aud_glm > log_j165_aud_glm 2> err_j165_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j166_aud_glm > log_j166_aud_glm 2> err_j166_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j167_aud_glm > log_j167_aud_glm 2> err_j167_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j168_aud_glm > log_j168_aud_glm 2> err_j168_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j169_aud_glm > log_j169_aud_glm 2> err_j169_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j170_aud_glm > log_j170_aud_glm 2> err_j170_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j171_aud_glm > log_j171_aud_glm 2> err_j171_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j172_aud_glm > log_j172_aud_glm 2> err_j172_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j173_aud_glm > log_j173_aud_glm 2> err_j173_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j174_aud_glm > log_j174_aud_glm 2> err_j174_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j175_aud_glm > log_j175_aud_glm 2> err_j175_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j176_aud_glm > log_j176_aud_glm 2> err_j176_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j177_aud_glm > log_j177_aud_glm 2> err_j177_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j178_aud_glm > log_j178_aud_glm 2> err_j178_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j179_aud_glm > log_j179_aud_glm 2> err_j179_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j180_aud_glm > log_j180_aud_glm 2> err_j180_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j181_aud_glm > log_j181_aud_glm 2> err_j181_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j182_aud_glm > log_j182_aud_glm 2> err_j182_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j183_aud_glm > log_j183_aud_glm 2> err_j183_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j184_aud_glm > log_j184_aud_glm 2> err_j184_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j185_aud_glm > log_j185_aud_glm 2> err_j185_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j186_aud_glm > log_j186_aud_glm 2> err_j186_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j187_aud_glm > log_j187_aud_glm 2> err_j187_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j188_aud_glm > log_j188_aud_glm 2> err_j188_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j189_aud_glm > log_j189_aud_glm 2> err_j189_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j190_aud_glm > log_j190_aud_glm 2> err_j190_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j191_aud_glm > log_j191_aud_glm 2> err_j191_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j192_aud_glm > log_j192_aud_glm 2> err_j192_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j193_aud_glm > log_j193_aud_glm 2> err_j193_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j194_aud_glm > log_j194_aud_glm 2> err_j194_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j195_aud_glm > log_j195_aud_glm 2> err_j195_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j196_aud_glm > log_j196_aud_glm 2> err_j196_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j197_aud_glm > log_j197_aud_glm 2> err_j197_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j198_aud_glm > log_j198_aud_glm 2> err_j198_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j199_aud_glm > log_j199_aud_glm 2> err_j199_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j200_aud_glm > log_j200_aud_glm 2> err_j200_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j201_aud_glm > log_j201_aud_glm 2> err_j201_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j202_aud_glm > log_j202_aud_glm 2> err_j202_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j203_aud_glm > log_j203_aud_glm 2> err_j203_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j204_aud_glm > log_j204_aud_glm 2> err_j204_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j205_aud_glm > log_j205_aud_glm 2> err_j205_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j206_aud_glm > log_j206_aud_glm 2> err_j206_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j207_aud_glm > log_j207_aud_glm 2> err_j207_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j208_aud_glm > log_j208_aud_glm 2> err_j208_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j209_aud_glm > log_j209_aud_glm 2> err_j209_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j210_aud_glm > log_j210_aud_glm 2> err_j210_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j211_aud_glm > log_j211_aud_glm 2> err_j211_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j212_aud_glm > log_j212_aud_glm 2> err_j212_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j213_aud_glm > log_j213_aud_glm 2> err_j213_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j214_aud_glm > log_j214_aud_glm 2> err_j214_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j215_aud_glm > log_j215_aud_glm 2> err_j215_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j216_aud_glm > log_j216_aud_glm 2> err_j216_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j217_aud_glm > log_j217_aud_glm 2> err_j217_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j218_aud_glm > log_j218_aud_glm 2> err_j218_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j219_aud_glm > log_j219_aud_glm 2> err_j219_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j220_aud_glm > log_j220_aud_glm 2> err_j220_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j221_aud_glm > log_j221_aud_glm 2> err_j221_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j222_aud_glm > log_j222_aud_glm 2> err_j222_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j223_aud_glm > log_j223_aud_glm 2> err_j223_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j224_aud_glm > log_j224_aud_glm 2> err_j224_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j225_aud_glm > log_j225_aud_glm 2> err_j225_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j226_aud_glm > log_j226_aud_glm 2> err_j226_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j227_aud_glm > log_j227_aud_glm 2> err_j227_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j228_aud_glm > log_j228_aud_glm 2> err_j228_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j229_aud_glm > log_j229_aud_glm 2> err_j229_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j230_aud_glm > log_j230_aud_glm 2> err_j230_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j231_aud_glm > log_j231_aud_glm 2> err_j231_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j232_aud_glm > log_j232_aud_glm 2> err_j232_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j233_aud_glm > log_j233_aud_glm 2> err_j233_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j234_aud_glm > log_j234_aud_glm 2> err_j234_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j235_aud_glm > log_j235_aud_glm 2> err_j235_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j236_aud_glm > log_j236_aud_glm 2> err_j236_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j237_aud_glm > log_j237_aud_glm 2> err_j237_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j238_aud_glm > log_j238_aud_glm 2> err_j238_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j239_aud_glm > log_j239_aud_glm 2> err_j239_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j240_aud_glm > log_j240_aud_glm 2> err_j240_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j241_aud_glm > log_j241_aud_glm 2> err_j241_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j242_aud_glm > log_j242_aud_glm 2> err_j242_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j243_aud_glm > log_j243_aud_glm 2> err_j243_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j244_aud_glm > log_j244_aud_glm 2> err_j244_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j245_aud_glm > log_j245_aud_glm 2> err_j245_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j246_aud_glm > log_j246_aud_glm 2> err_j246_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j247_aud_glm > log_j247_aud_glm 2> err_j247_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j248_aud_glm > log_j248_aud_glm 2> err_j248_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j249_aud_glm > log_j249_aud_glm 2> err_j249_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j250_aud_glm > log_j250_aud_glm 2> err_j250_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j251_aud_glm > log_j251_aud_glm 2> err_j251_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j252_aud_glm > log_j252_aud_glm 2> err_j252_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j253_aud_glm > log_j253_aud_glm 2> err_j253_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j254_aud_glm > log_j254_aud_glm 2> err_j254_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j255_aud_glm > log_j255_aud_glm 2> err_j255_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j256_aud_glm > log_j256_aud_glm 2> err_j256_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j257_aud_glm > log_j257_aud_glm 2> err_j257_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j258_aud_glm > log_j258_aud_glm 2> err_j258_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j259_aud_glm > log_j259_aud_glm 2> err_j259_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j260_aud_glm > log_j260_aud_glm 2> err_j260_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j261_aud_glm > log_j261_aud_glm 2> err_j261_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j262_aud_glm > log_j262_aud_glm 2> err_j262_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j263_aud_glm > log_j263_aud_glm 2> err_j263_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j264_aud_glm > log_j264_aud_glm 2> err_j264_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j265_aud_glm > log_j265_aud_glm 2> err_j265_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j266_aud_glm > log_j266_aud_glm 2> err_j266_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j267_aud_glm > log_j267_aud_glm 2> err_j267_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j268_aud_glm > log_j268_aud_glm 2> err_j268_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j269_aud_glm > log_j269_aud_glm 2> err_j269_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j270_aud_glm > log_j270_aud_glm 2> err_j270_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j271_aud_glm > log_j271_aud_glm 2> err_j271_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j272_aud_glm > log_j272_aud_glm 2> err_j272_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j273_aud_glm > log_j273_aud_glm 2> err_j273_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j274_aud_glm > log_j274_aud_glm 2> err_j274_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j275_aud_glm > log_j275_aud_glm 2> err_j275_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j276_aud_glm > log_j276_aud_glm 2> err_j276_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j277_aud_glm > log_j277_aud_glm 2> err_j277_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j278_aud_glm > log_j278_aud_glm 2> err_j278_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j279_aud_glm > log_j279_aud_glm 2> err_j279_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j280_aud_glm > log_j280_aud_glm 2> err_j280_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j281_aud_glm > log_j281_aud_glm 2> err_j281_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j282_aud_glm > log_j282_aud_glm 2> err_j282_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j283_aud_glm > log_j283_aud_glm 2> err_j283_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j284_aud_glm > log_j284_aud_glm 2> err_j284_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j285_aud_glm > log_j285_aud_glm 2> err_j285_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j286_aud_glm > log_j286_aud_glm 2> err_j286_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j287_aud_glm > log_j287_aud_glm 2> err_j287_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j288_aud_glm > log_j288_aud_glm 2> err_j288_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j289_aud_glm > log_j289_aud_glm 2> err_j289_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j290_aud_glm > log_j290_aud_glm 2> err_j290_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j291_aud_glm > log_j291_aud_glm 2> err_j291_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j292_aud_glm > log_j292_aud_glm 2> err_j292_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j293_aud_glm > log_j293_aud_glm 2> err_j293_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j294_aud_glm > log_j294_aud_glm 2> err_j294_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j295_aud_glm > log_j295_aud_glm 2> err_j295_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j296_aud_glm > log_j296_aud_glm 2> err_j296_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j297_aud_glm > log_j297_aud_glm 2> err_j297_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j298_aud_glm > log_j298_aud_glm 2> err_j298_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j299_aud_glm > log_j299_aud_glm 2> err_j299_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j300_aud_glm > log_j300_aud_glm 2> err_j300_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j301_aud_glm > log_j301_aud_glm 2> err_j301_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j302_aud_glm > log_j302_aud_glm 2> err_j302_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j303_aud_glm > log_j303_aud_glm 2> err_j303_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j304_aud_glm > log_j304_aud_glm 2> err_j304_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j305_aud_glm > log_j305_aud_glm 2> err_j305_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j306_aud_glm > log_j306_aud_glm 2> err_j306_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j307_aud_glm > log_j307_aud_glm 2> err_j307_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j308_aud_glm > log_j308_aud_glm 2> err_j308_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j309_aud_glm > log_j309_aud_glm 2> err_j309_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j310_aud_glm > log_j310_aud_glm 2> err_j310_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j311_aud_glm > log_j311_aud_glm 2> err_j311_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j312_aud_glm > log_j312_aud_glm 2> err_j312_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j313_aud_glm > log_j313_aud_glm 2> err_j313_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j314_aud_glm > log_j314_aud_glm 2> err_j314_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j315_aud_glm > log_j315_aud_glm 2> err_j315_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j316_aud_glm > log_j316_aud_glm 2> err_j316_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j317_aud_glm > log_j317_aud_glm 2> err_j317_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j318_aud_glm > log_j318_aud_glm 2> err_j318_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j319_aud_glm > log_j319_aud_glm 2> err_j319_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j320_aud_glm > log_j320_aud_glm 2> err_j320_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j321_aud_glm > log_j321_aud_glm 2> err_j321_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j322_aud_glm > log_j322_aud_glm 2> err_j322_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j323_aud_glm > log_j323_aud_glm 2> err_j323_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j324_aud_glm > log_j324_aud_glm 2> err_j324_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j325_aud_glm > log_j325_aud_glm 2> err_j325_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j326_aud_glm > log_j326_aud_glm 2> err_j326_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j327_aud_glm > log_j327_aud_glm 2> err_j327_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j328_aud_glm > log_j328_aud_glm 2> err_j328_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j329_aud_glm > log_j329_aud_glm 2> err_j329_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j330_aud_glm > log_j330_aud_glm 2> err_j330_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j331_aud_glm > log_j331_aud_glm 2> err_j331_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j332_aud_glm > log_j332_aud_glm 2> err_j332_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j333_aud_glm > log_j333_aud_glm 2> err_j333_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j334_aud_glm > log_j334_aud_glm 2> err_j334_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j335_aud_glm > log_j335_aud_glm 2> err_j335_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j336_aud_glm > log_j336_aud_glm 2> err_j336_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j337_aud_glm > log_j337_aud_glm 2> err_j337_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j338_aud_glm > log_j338_aud_glm 2> err_j338_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j339_aud_glm > log_j339_aud_glm 2> err_j339_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j340_aud_glm > log_j340_aud_glm 2> err_j340_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j341_aud_glm > log_j341_aud_glm 2> err_j341_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j342_aud_glm > log_j342_aud_glm 2> err_j342_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j343_aud_glm > log_j343_aud_glm 2> err_j343_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j344_aud_glm > log_j344_aud_glm 2> err_j344_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j345_aud_glm > log_j345_aud_glm 2> err_j345_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j346_aud_glm > log_j346_aud_glm 2> err_j346_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j347_aud_glm > log_j347_aud_glm 2> err_j347_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j348_aud_glm > log_j348_aud_glm 2> err_j348_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j349_aud_glm > log_j349_aud_glm 2> err_j349_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j350_aud_glm > log_j350_aud_glm 2> err_j350_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j351_aud_glm > log_j351_aud_glm 2> err_j351_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j352_aud_glm > log_j352_aud_glm 2> err_j352_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j353_aud_glm > log_j353_aud_glm 2> err_j353_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j354_aud_glm > log_j354_aud_glm 2> err_j354_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j355_aud_glm > log_j355_aud_glm 2> err_j355_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j356_aud_glm > log_j356_aud_glm 2> err_j356_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j357_aud_glm > log_j357_aud_glm 2> err_j357_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j358_aud_glm > log_j358_aud_glm 2> err_j358_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j359_aud_glm > log_j359_aud_glm 2> err_j359_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j360_aud_glm > log_j360_aud_glm 2> err_j360_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j361_aud_glm > log_j361_aud_glm 2> err_j361_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j362_aud_glm > log_j362_aud_glm 2> err_j362_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j363_aud_glm > log_j363_aud_glm 2> err_j363_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j364_aud_glm > log_j364_aud_glm 2> err_j364_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j365_aud_glm > log_j365_aud_glm 2> err_j365_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j366_aud_glm > log_j366_aud_glm 2> err_j366_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j367_aud_glm > log_j367_aud_glm 2> err_j367_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j368_aud_glm > log_j368_aud_glm 2> err_j368_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j369_aud_glm > log_j369_aud_glm 2> err_j369_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j370_aud_glm > log_j370_aud_glm 2> err_j370_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j371_aud_glm > log_j371_aud_glm 2> err_j371_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j372_aud_glm > log_j372_aud_glm 2> err_j372_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j373_aud_glm > log_j373_aud_glm 2> err_j373_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j374_aud_glm > log_j374_aud_glm 2> err_j374_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j375_aud_glm > log_j375_aud_glm 2> err_j375_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j376_aud_glm > log_j376_aud_glm 2> err_j376_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j377_aud_glm > log_j377_aud_glm 2> err_j377_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j378_aud_glm > log_j378_aud_glm 2> err_j378_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j379_aud_glm > log_j379_aud_glm 2> err_j379_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j380_aud_glm > log_j380_aud_glm 2> err_j380_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j381_aud_glm > log_j381_aud_glm 2> err_j381_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j382_aud_glm > log_j382_aud_glm 2> err_j382_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j383_aud_glm > log_j383_aud_glm 2> err_j383_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j384_aud_glm > log_j384_aud_glm 2> err_j384_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j385_aud_glm > log_j385_aud_glm 2> err_j385_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j386_aud_glm > log_j386_aud_glm 2> err_j386_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j387_aud_glm > log_j387_aud_glm 2> err_j387_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j388_aud_glm > log_j388_aud_glm 2> err_j388_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j389_aud_glm > log_j389_aud_glm 2> err_j389_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j390_aud_glm > log_j390_aud_glm 2> err_j390_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j391_aud_glm > log_j391_aud_glm 2> err_j391_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j392_aud_glm > log_j392_aud_glm 2> err_j392_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j393_aud_glm > log_j393_aud_glm 2> err_j393_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j394_aud_glm > log_j394_aud_glm 2> err_j394_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j395_aud_glm > log_j395_aud_glm 2> err_j395_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j396_aud_glm > log_j396_aud_glm 2> err_j396_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j397_aud_glm > log_j397_aud_glm 2> err_j397_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j398_aud_glm > log_j398_aud_glm 2> err_j398_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j399_aud_glm > log_j399_aud_glm 2> err_j399_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j400_aud_glm > log_j400_aud_glm 2> err_j400_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j401_aud_glm > log_j401_aud_glm 2> err_j401_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j402_aud_glm > log_j402_aud_glm 2> err_j402_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j403_aud_glm > log_j403_aud_glm 2> err_j403_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j404_aud_glm > log_j404_aud_glm 2> err_j404_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j405_aud_glm > log_j405_aud_glm 2> err_j405_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j406_aud_glm > log_j406_aud_glm 2> err_j406_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j407_aud_glm > log_j407_aud_glm 2> err_j407_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j408_aud_glm > log_j408_aud_glm 2> err_j408_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j409_aud_glm > log_j409_aud_glm 2> err_j409_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j410_aud_glm > log_j410_aud_glm 2> err_j410_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j411_aud_glm > log_j411_aud_glm 2> err_j411_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j412_aud_glm > log_j412_aud_glm 2> err_j412_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j413_aud_glm > log_j413_aud_glm 2> err_j413_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j414_aud_glm > log_j414_aud_glm 2> err_j414_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j415_aud_glm > log_j415_aud_glm 2> err_j415_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j416_aud_glm > log_j416_aud_glm 2> err_j416_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j417_aud_glm > log_j417_aud_glm 2> err_j417_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j418_aud_glm > log_j418_aud_glm 2> err_j418_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j419_aud_glm > log_j419_aud_glm 2> err_j419_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j420_aud_glm > log_j420_aud_glm 2> err_j420_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j421_aud_glm > log_j421_aud_glm 2> err_j421_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j422_aud_glm > log_j422_aud_glm 2> err_j422_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j423_aud_glm > log_j423_aud_glm 2> err_j423_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j424_aud_glm > log_j424_aud_glm 2> err_j424_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j425_aud_glm > log_j425_aud_glm 2> err_j425_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j426_aud_glm > log_j426_aud_glm 2> err_j426_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j427_aud_glm > log_j427_aud_glm 2> err_j427_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j428_aud_glm > log_j428_aud_glm 2> err_j428_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j429_aud_glm > log_j429_aud_glm 2> err_j429_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j430_aud_glm > log_j430_aud_glm 2> err_j430_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j431_aud_glm > log_j431_aud_glm 2> err_j431_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j432_aud_glm > log_j432_aud_glm 2> err_j432_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j433_aud_glm > log_j433_aud_glm 2> err_j433_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j434_aud_glm > log_j434_aud_glm 2> err_j434_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j435_aud_glm > log_j435_aud_glm 2> err_j435_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j436_aud_glm > log_j436_aud_glm 2> err_j436_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j437_aud_glm > log_j437_aud_glm 2> err_j437_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j438_aud_glm > log_j438_aud_glm 2> err_j438_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j439_aud_glm > log_j439_aud_glm 2> err_j439_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j440_aud_glm > log_j440_aud_glm 2> err_j440_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j441_aud_glm > log_j441_aud_glm 2> err_j441_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j442_aud_glm > log_j442_aud_glm 2> err_j442_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j443_aud_glm > log_j443_aud_glm 2> err_j443_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j444_aud_glm > log_j444_aud_glm 2> err_j444_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j445_aud_glm > log_j445_aud_glm 2> err_j445_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j446_aud_glm > log_j446_aud_glm 2> err_j446_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j447_aud_glm > log_j447_aud_glm 2> err_j447_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j448_aud_glm > log_j448_aud_glm 2> err_j448_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j449_aud_glm > log_j449_aud_glm 2> err_j449_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j450_aud_glm > log_j450_aud_glm 2> err_j450_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j451_aud_glm > log_j451_aud_glm 2> err_j451_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j452_aud_glm > log_j452_aud_glm 2> err_j452_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j453_aud_glm > log_j453_aud_glm 2> err_j453_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j454_aud_glm > log_j454_aud_glm 2> err_j454_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j455_aud_glm > log_j455_aud_glm 2> err_j455_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j456_aud_glm > log_j456_aud_glm 2> err_j456_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j457_aud_glm > log_j457_aud_glm 2> err_j457_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j458_aud_glm > log_j458_aud_glm 2> err_j458_aud_glm 
bash /network/lustre/iss02/cohen/data/Fabien_official/SYNESTHEX/scripts/aud_glm/j459_aud_glm > log_j459_aud_glm 2> err_j459_aud_glm 
